"""
Django settings for humming_brazil_covid19 project.

Generated by 'django-admin startproject' using Django 3.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import dj_database_url

from humming_brazil_covid19.settings.base import *

# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

DEBUG = False
DATABASE_URL = os.environ.get("DATABASE_URL", "")
DATABASES = {"default": dj_database_url.config(conn_max_age=600, ssl_require=True)}
