# Generated by Django 3.0.4 on 2020-03-11 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='updated_at',
            field=models.DateTimeField(),
        ),
    ]
