# Generated by Django 3.0.4 on 2020-03-31 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0004_auto_20200331_0947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='refuses',
        ),
        migrations.RemoveField(
            model_name='case',
            name='suspects',
        ),
    ]
