# Generated by Django 3.0.4 on 2020-03-31 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0005_auto_20200331_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='region',
            field=models.CharField(choices=[('NE', 'Nordeste'), ('NO', 'Norte'), ('CO', 'Centro-Oeste'), ('SU', 'Sul'), ('SE', 'Sudeste')], max_length=2),
        ),
    ]
