# Generated by Django 3.0.4 on 2020-05-06 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0006_auto_20200331_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='cases',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='case',
            name='deaths',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
